sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: never

branches:
  only:
    - master

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=trunk

#Install Docker Compose
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  # Export composer
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  # Install plugin with composer
  # Create a production-like build
  - composer install --prefer-dist --optimize-autoloader --no-progress
  # Install test environment using composer script
  - composer wp-install
script:
  # Run All Tests and Code Sniffs and Fixes
  - composer tests