<?php


namespace CalderaLearn\RestSearch\Tests\Mock;

class AlwaysFilterWPQuery extends \CalderaLearn\RestSearch\FilterWPQuery
{
	/** @inheritdoc */
	public static function shouldFilter($postsOrNull) : bool
	{
		return is_null($postsOrNull);
	}

	/** @inheritdoc */
	public static function getPosts() : array
	{
		if (function_exists('wp_insert_post')) {
			$posts = [];
			$id = wp_insert_post(['post_title' => rand(), 'post_content' => rand() ]);
			$posts[] = get_post($id);
			$id = wp_insert_post(['post_title' => rand(), 'post_content' => rand() ]);
			$posts[] = get_post($id);
			return $posts;
		}
		return parent::getPosts(); // TODO: Change the autogenerated stub
	}
}
